name: 'Setup Conda'
description: 'Create conda environment for GitHub Action Job'

runs:
  using: "composite"
  steps:
    - name: Cache Conda Packages
      uses: actions/cache@v3
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-packages-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        miniforge-variant: Mambaforge
        use-mamba: true
        auto-update-conda: false
        activate-environment: hackweek
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for conda package cache to work properly!

    - name: Cache Entire Conda Environment
      id: cache-env
      uses: actions/cache@v3
      env:
        CACHE_NUMBER: 0
      with:
        path: ${{ env.CONDA }}/envs
        key:
          ${{ runner.os }}-conda-environment-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - name: Update Conda Environment
      if: steps.cache-env.outputs.cache-hit != 'true'
      shell: bash -l {0}
      run: mamba env update -n hackweek -f environment.yml

    - name: List conda packages
      shell: bash -l {0}
      run: |
        conda list
